### ISSUE TITLE
mariadb image without OS

### ISSUE THREAD

**Issue by rvdkraan** [CircleCI-Public/cimg-mariadb#11]
In our workflow we use two docker images. 
Image 1 : Build Tools 
Image 2 : MariaDB  for testing and configuration using the enviromental variables.  

Previously the image was similar to https://hub.docker.com/_/mariadb 
Can this image be made with so it uses the environmetal variables for configuration?

**Comment by BytesGuy** [comment]
Hi @rvdkraan All "next-gen" CircleCI convenience images are based on a common image - [CircleCI-Public/cimg-base](https://github.com/CircleCI-Public/cimg-base). This allows us better control over all the images as a whole, rather than inheriting from multiple different upstream images.

Which environment variables are you trying to set that are not working?

**Comment by rvdkraan** [comment]
environment: 
          MYSQL_DATABASE: dbName
          MYSQL_USER: dbUser
          MYSQL_PASSWORD: dbPassword

**Comment by BytesGuy** [comment]
@rvdkraan I cannot reproduce any issue with setting the environment variables described above. My sample config is as follows:

https://gist.github.com/BytesGuy/9aac2a005ddd1363b66402275c14b1d0

We do not have any plans to offer next-gen images based on different base images at this time. As such I would advise forking an existing image (like the old legacy image, or the official image you linked in the original post) that suits your needs and modify it as required: https://circleci.com/docs/2.0/custom-images/

**Comment by rvdkraan** [comment]
Hi BytesGuy
is your test working because both your docker images are based on  cimg/base? 
Can cimg/mariadb only be used together with an  cimg/base instead of a custom image. 
Our image was generated using the wizard.

**Comment by BytesGuy** [comment]
Hi @rvdkraan That's good news! I think you were affected by #12 which is now fixed 😄
