### ISSUE TITLE
pwgen not found

### ISSUE THREAD

**Issue by TimoKramer** [CircleCI-Public/cimg-mariadb#29]
The image doesn't start unfortunately:
```
/usr/local/bin/docker-entrypoint.sh: line 271: pwgen: command not found
```

**Comment by BytesGuy** [comment]
@TimoKramer Which image version are you referring to and is this happening in a CircleCI job?

**Comment by TimoKramer** [comment]
You can see it failing [here](https://app.circleci.com/pipelines/github/replikativ/datahike-jdbc/53/workflows/4ea33cd2-6973-4402-a68a-346c94713338/jobs/174). I am running this command:
```
docker run --detach --publish 3306:3306 --env MYSQL_RANDOM_ROOT_PASSWORD=true --env MYSQL_DATABASE=config-test --env MYSQL_USER=alice --env MYSQL_PASSWORD=foo
```
so it might actually be related to the random-root-pw...

**Comment by BytesGuy** [comment]
@TimoKramer Thanks for the additional information. I have opened a PR for this: #30

**Comment by BytesGuy** [comment]
@TimoKramer this is now merged so it will apply from the next image version we release. Thanks for reporting this issue :)
